// Code generated by goctl. DO NOT EDIT.
package types

type CreateUserReq struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserResp struct {
	Id int64 `json:"id"`
}
